apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig


metadata:
  name: vmsl-dr
  region: us-west-1


vpc:
  subnets:
    private:
      us-west-1a: { id: PRIVATE_SUBNET_ID_1 }
      us-west-1b: { id: PRIVATE_SUBNET_ID_2 }
    

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]   


managedNodeGroups:
  - name: vmsl-dr
    volumeType: gp2
    amiFamily: AmazonLinux2
    minSize: 1
    maxSize: 2
    desiredCapacity: 2
    volumeSize: 10
    volumeEncrypted: true
    instanceType: t3.medium
    privateNetworking: true
    tags:
      nodegroup-role: worker  
      Environment: dr 
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true